### ISSUE TITLE
Class 'Yii\base\Widget' not found

### ISSUE THREAD

**Issue by heanluen** [speixoto/yii2-amcharts#4]
line 27 should be use yii; not Yii;

**Comment by ebtc** [comment]
The code should read `\yii\base\Widget`, it misses the trailing slash.

**Comment by ebtc** [comment]
Actually ... it seems that composer pulls some old code for the Widget.php file. There it misses the slash, but your codebase has it in.

**Comment by zabachok** [comment]
+1 I have this problem too; If I change it:
`class Widget extends yii\base\Widget`
to:
`class Widget extends \yii\base\Widget`
it starts to work!!!
